
spring:
  port: 8080
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:com/example/demo/dao/UserMapper.xml
  type-aliases-package: com.example.demo.entity